const GROUP="ATEEZ";
const $=id=>document.getElementById(id);
const cardList=$("cardList"),searchInput=$("searchInput"),modal=$("modal"),addBtn=$("addBtn"),saveBtn=$("saveBtn"),typeInput=$("typeInput"),dynamicFields=$("dynamicFields"),fileInput=$("fileInput"),frame=$("frame"),frameImg=$("frameImg"),deleteBar=$("deleteBar"),deleteCount=$("deleteCount"),groupTabs=$("groupTabs"),typeTabs=$("typeTabs");
let items=[],albums={},catalog={"특전":[],"럭드":[],"팬키트":[],"시즌그리팅":[],"MD":[]},currentType="all",currentAlbum="all",deleteMode=false,currentCard=null,selectedIds=new Set(),pendingImage=null,objectUrls=[];
let sortableReady=false,dbReady=null;
const catalogTypes=["특전","럭드","팬키트","시즌그리팅","MD"];
function makeId(){return(globalThis.crypto&&typeof crypto.randomUUID==="function")?crypto.randomUUID():"card-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2)+"-"+Math.random().toString(36).slice(2)}
function loadSortable(){return new Promise(resolve=>{if(window.Sortable){sortableReady=true;return resolve()}const sc=document.createElement("script");sc.src="https://cdn.jsdelivr.net/npm/sortablejs@1.15.6/Sortable.min.js";sc.onload=()=>{sortableReady=true;resolve()};sc.onerror=()=>resolve();document.head.appendChild(sc)})}
async function saveRowOrder(row){const cards=[...row.querySelectorAll(".card")];for(let i=0;i<cards.length;i++){const id=cards[i].dataset.id,card=items.find(x=>String(x.id)===String(id));if(card){card.order=i;await saveCard(card)}}}
function enableDrag(row){if(!sortableReady||row.dataset.sortable==="1")return;row.dataset.sortable="1";new Sortable(row,{animation:160,ghostClass:"dragging",dragClass:"dragging",delay:80,delayOnTouchOnly:true,onEnd:()=>saveRowOrder(row).then(()=>{items.sort((a,b)=>(a.order??999999)-(b.order??999999))})})}
$("appTitle").textContent=`Poca List · ${GROUP}`;
function saveSettings(){localStorage.setItem(GROUP+"_settings",JSON.stringify({albums,catalog}))}
function normalizeCatalog(){const out={};for(const t of catalogTypes)out[t]=Array.isArray(catalog?.[t])?[...new Set(catalog[t].map(String).map(x=>x.trim()).filter(Boolean))]:[];catalog=out}
function loadSettings(){try{const d=JSON.parse(localStorage.getItem(GROUP+"_settings")||"{}");albums=d.albums&&typeof d.albums==="object"?d.albums:{};for(const a of Object.keys(albums))if(!Array.isArray(albums[a]))albums[a]=[];catalog=d.catalog&&typeof d.catalog==="object"?d.catalog:catalog;normalizeCatalog()}catch{albums={};normalizeCatalog()}}
function getLastAdd(){try{return JSON.parse(localStorage.getItem(GROUP+"_lastAdd")||"{}")||{}}catch{return{}}}
function saveLastAdd(patch){const d={...getLastAdd(),...patch};localStorage.setItem(GROUP+"_lastAdd",JSON.stringify(d))}
function closeModal(){modal.classList.add("hidden")}
function openAdmin(){renderAdmin();renderMemberAdminSelect();renderCatalogAdmin();$("adminPanel").classList.remove("hidden")}
function closeAdmin(){$("adminPanel").classList.add("hidden")}
async function compressImage(file){const b=await createImageBitmap(file),MAX=1000;let w=b.width,h=b.height;if(w>MAX||h>MAX){const s=Math.min(MAX/w,MAX/h);w=Math.round(w*s);h=Math.round(h*s)}const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(b,0,0,w,h);b.close();return new Promise((res,rej)=>c.toBlob(x=>x?res(x):rej(new Error("압축 실패")),"image/webp",.9))}
fileInput.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{pendingImage=await compressImage(f);$("imageStatus").textContent=`준비 완료 · ${(pendingImage.size/1024).toFixed(0)} KB`}catch(err){alert("이미지를 처리하지 못했어.")}}
function openAddModal(){const last=getLastAdd();typeInput.value=catalogTypes.includes(last.type)||last.type==="앨범"?last.type:"앨범";renderDynamicFields(last);$("nameInput").value="";fileInput.value="";pendingImage=null;$("imageStatus").textContent="";modal.classList.remove("hidden")}
addBtn.onclick=openAddModal;
typeInput.onchange=()=>{const last=getLastAdd();saveLastAdd({type:typeInput.value});renderDynamicFields({...last,type:typeInput.value})};
function renderDynamicFields(state={}){dynamicFields.innerHTML="";const type=typeInput.value;if(type==="앨범"){const a=document.createElement("select");a.id="albumSelect";a.innerHTML="";const ns=Object.keys(albums);if(!ns.length){a.innerHTML='<option value="">먼저 앨범을 추가해줘</option>'}else ns.forEach(n=>{const o=document.createElement("option");o.value=n;o.textContent=n;a.appendChild(o)});if(state.album&&ns.includes(state.album))a.value=state.album;dynamicFields.appendChild(a);const m=document.createElement("select");m.id="memberInput";dynamicFields.appendChild(m);renderMemberSelect(state.member);a.onchange=()=>{saveLastAdd({type:"앨범",album:a.value});renderMemberSelect();};m.onchange=()=>saveLastAdd({member:m.value});return}
const label=document.createElement("label");label.textContent=type+" 선택";const s=document.createElement("select");s.id="detailSelect";const ns=Array.isArray(catalog[type])?catalog[type]:[];if(!ns.length){const o=document.createElement("option");o.value="";o.textContent=`관리에서 ${type} 항목을 먼저 추가해줘`;s.appendChild(o)}else ns.forEach(n=>{const o=document.createElement("option");o.value=n;o.textContent=n;s.appendChild(o)});if(state.detail&&ns.includes(state.detail))s.value=state.detail;dynamicFields.append(label,s);s.onchange=()=>saveLastAdd({type,detail:s.value})}
function renderMemberSelect(preferred){const a=$("albumSelect"),m=$("memberInput");if(!a||!m)return;m.innerHTML="";const ms=albums[a.value]||[];if(!ms.length){m.innerHTML='<option value="">먼저 멤버를 추가해줘</option>';return}ms.forEach(n=>{const o=document.createElement("option");o.value=n;o.textContent=n;m.appendChild(o)});if(preferred&&ms.includes(preferred))m.value=preferred;saveLastAdd({type:"앨범",album:a.value,member:m.value})}
async function addCard(){const type=typeInput.value,name=$("nameInput").value.trim();let album="",member="",detail="";if(type==="앨범"){album=$("albumSelect")?.value||"";member=$("memberInput")?.value||"";detail=album}else detail=$("detailSelect")?.value||"";if(type==="앨범"&&!album)return alert("앨범을 먼저 선택해줘.");if(type==="앨범"&&!member)return alert("멤버를 먼저 추가/선택해줘.");if(type!=="앨범"&&!detail)return alert(`${type} 항목을 먼저 추가해줘.`);if(!pendingImage)return alert("이미지를 선택해줘.");if(items.some(x=>x.album===album&&x.member===member&&x.type===type&&x.detail===detail))return alert("같은 정보의 포카가 이미 있어!");const c={id:makeId(),order:items.length,name,album,member,type,detail,img:pendingImage,owned:false,selected:false,createdAt:Date.now()};saveBtn.disabled=true;try{await dbReady;await saveCard(c);items.push(c);saveLastAdd({type,album,member,detail});pendingImage=null;render();closeModal()}catch(err){alert("포카를 저장하지 못했어.\n"+(err?.message||err))}finally{saveBtn.disabled=false}}
saveBtn.onclick=addCard;
function revokeUrls(){objectUrls.forEach(URL.revokeObjectURL);objectUrls=[]}function imageURL(c){if(c.img instanceof Blob){const u=URL.createObjectURL(c.img);objectUrls.push(u);return u}return typeof c.img==="string"?c.img:""}
function render(){revokeUrls();cardList.innerHTML="";const q=searchInput.value.trim().toLowerCase(),f=items.filter(i=>(currentAlbum==="all"||i.album===currentAlbum)&&(currentType==="all"||i.type===currentType)&&[i.name,i.album,i.member,i.detail,i.type].join(" ").toLowerCase().includes(q)),g={};f.forEach(i=>(g[i.album||i.type]??=[]).push(i));const names=[...Object.keys(albums),...Object.keys(g).filter(x=>!albums[x])];for(const a of names){const list=g[a]||[];if(!list.length)continue;const s=document.createElement("section");s.className="album-section";const owned=list.filter(x=>x.owned).length,p=Math.round(owned/list.length*100);s.innerHTML=`<div class="album-title ${owned===list.length?"complete":""}"><h2>${escapeHTML(a)}</h2><span>${owned} / ${list.length}${owned===list.length?" 🔥 100%":""}</span></div><div class="progress-wrap"><div class="progress-bar" style="width:${p}%"></div></div><div class="album-row"></div>`;const row=s.querySelector(".album-row");list.sort((x,y)=>(x.order??999999)-(y.order??999999));list.forEach(card=>{const c=document.createElement("div");c.className="card"+(card.owned?" owned":"");c.dataset.id=card.id;if(deleteMode&&selectedIds.has(card.id))c.classList.add("selected");const img=document.createElement("img");img.loading="lazy";img.decoding="async";img.className=card.owned?"loaded":"loading";img.src=imageURL(card);img.alt=card.name||card.member||"photocard";img.onload=()=>{if(card.owned)img.classList.add("loaded");else img.classList.add("loading")};c.appendChild(img);c.onclick=async()=>{if(deleteMode){selectedIds.has(card.id)?selectedIds.delete(card.id):selectedIds.add(card.id);c.classList.toggle("selected",selectedIds.has(card.id));updateDeleteCount();return}card.owned=!card.owned;c.classList.toggle("owned",card.owned);img.classList.toggle("loaded",card.owned);img.classList.toggle("loading",!card.owned);try{await saveCard(card);renderProgressOnly();const title=c.closest(".album-section")?.querySelector(".album-title span");if(title){const n=items.filter(x=>x.album===card.album&&x.owned).length,total=items.filter(x=>x.album===card.album).length;title.textContent=`${n} / ${total}${n===total?" 🔥 100%":""}`}}catch(err){card.owned=!card.owned;c.classList.toggle("owned",card.owned);img.classList.toggle("loaded",card.owned);img.classList.toggle("loading",!card.owned);alert("보유 상태를 저장하지 못했어.\n"+(err?.message||err))}};c.ondblclick=()=>{if(!deleteMode)openFrame(card)};row.appendChild(c)});enableDrag(row);cardList.appendChild(s)}renderTabs();renderProgressOnly()}
function renderProgressOnly(){const t=items.length,o=items.filter(x=>x.owned).length,p=t?Math.round(o/t*100):0;$("progressText").textContent=`${o} / ${t} (${p}%)`;$("collectionInfo").textContent=`${GROUP} · ${t}장`}
function renderTabs(){groupTabs.innerHTML="";const all=document.createElement("button");all.textContent="전체";all.classList.toggle("active",currentAlbum==="all");all.onclick=()=>{currentAlbum="all";render()};groupTabs.appendChild(all);Object.keys(albums).forEach(a=>{const b=document.createElement("button");b.textContent=a;b.classList.toggle("active",currentAlbum===a);b.onclick=()=>{currentAlbum=a;render()};groupTabs.appendChild(b)});typeTabs.innerHTML="";["all","앨범","특전","럭드","팬키트","시즌그리팅","MD"].forEach(t=>{const b=document.createElement("button");b.textContent=t==="all"?"전체":t;b.classList.toggle("active",currentType===t);b.onclick=()=>{currentType=t;render()};typeTabs.appendChild(b)})}
function renderAdmin(){const l=$("albumAdminList");l.innerHTML="";const ns=Object.keys(albums);if(!ns.length){l.innerHTML="<p>아직 앨범이 없어.</p>";return}ns.forEach(a=>{const r=document.createElement("div");r.style.marginBottom="8px";r.innerHTML=`<b>${escapeHTML(a)}</b> · ${(albums[a]||[]).length}명`;const d=document.createElement("button");d.textContent="삭제";d.style.marginLeft="8px";d.onclick=()=>{if(!confirm(`"${a}" 앨범을 목록에서 삭제할까?`))return;delete albums[a];if(currentAlbum===a)currentAlbum="all";saveSettings();renderAdmin();renderMemberAdminSelect();renderDynamicFields(getLastAdd());render()};r.appendChild(d);l.appendChild(r)})}
function addAlbum(){const i=$("newAlbum"),n=i.value.trim();if(!n)return alert("앨범 이름을 입력해줘.");if(albums[n])return alert("이미 있는 앨범이야.");albums[n]=[];saveSettings();i.value="";renderMemberAdminSelect();renderDynamicFields({type:"앨범",album:n});renderAdmin();render();saveLastAdd({type:"앨범",album:n});alert(`"${n}" 앨범 추가 완료!`)}
function addMember(){const s=$("memberAlbum"),i=$("newMember"),a=s.value,n=i.value.trim();if(!a)return alert("먼저 앨범을 선택해줘.");if(!n)return alert("멤버 이름을 입력해줘.");if(!Array.isArray(albums[a]))albums[a]=[];if(albums[a].includes(n))return alert("이미 등록된 멤버야.");albums[a].push(n);saveSettings();i.value="";renderMemberAdminSelect();s.value=a;renderDynamicFields({type:"앨범",album:a,member:n});renderAdmin();render();saveLastAdd({type:"앨범",album:a,member:n});alert(`"${a}"에 ${n} 추가 완료!`)}
function renderMemberAdminSelect(){const s=$("memberAlbum");if(!s)return;s.innerHTML="";const ns=Object.keys(albums);if(!ns.length){s.innerHTML='<option value="">먼저 앨범을 추가해줘</option>';return}const last=getLastAdd();ns.forEach(a=>{const o=document.createElement("option");o.value=a;o.textContent=a;s.appendChild(o)});if(last.album&&ns.includes(last.album))s.value=last.album}
function renderCatalogAdmin(){const t=$("catalogType");const type=t.value;const l=$("catalogAdminList");l.innerHTML="";(catalog[type]||[]).forEach(n=>{const r=document.createElement("div");r.style.marginBottom="6px";r.innerHTML=`<span>${escapeHTML(n)}</span>`;const d=document.createElement("button");d.textContent="삭제";d.style.marginLeft="8px";d.onclick=()=>{catalog[type]=catalog[type].filter(x=>x!==n);saveSettings();renderCatalogAdmin();};r.appendChild(d);l.appendChild(r)});if(!catalog[type]?.length)l.innerHTML="<p>아직 등록된 항목이 없어.</p>"}
$("catalogType").onchange=renderCatalogAdmin;
function addCatalogItem(){const type=$("catalogType").value,n=$("newCatalogItem").value.trim();if(!n)return alert("항목 이름을 입력해줘.");catalog[type]??=[];if(catalog[type].includes(n))return alert("이미 등록된 항목이야.");catalog[type].push(n);saveSettings();$("newCatalogItem").value="";renderCatalogAdmin();if(typeInput.value===type)renderDynamicFields({type,detail:n});alert(`"${n}" 추가 완료!`)}
function toggleDeleteMode(){deleteMode=!deleteMode;selectedIds.clear();document.body.classList.toggle("delete-mode",deleteMode);deleteBar.classList.toggle("hidden",!deleteMode);updateDeleteCount();render()}function updateDeleteCount(){$("deleteCount").textContent=`${selectedIds.size}개 선택됨`}
async function deleteSelected(){if(!selectedIds.size)return alert("선택된 포카가 없어.");if(!confirm(`선택된 ${selectedIds.size}개 삭제할까?`))return;for(const id of selectedIds)await deleteCard(id);items=items.filter(x=>!selectedIds.has(x.id));selectedIds.clear();deleteMode=false;document.body.classList.remove("delete-mode");deleteBar.classList.add("hidden");render()}
function openFrame(c){currentCard=c;if(frameImg.src.startsWith("blob:"))URL.revokeObjectURL(frameImg.src);frameImg.src=c.img instanceof Blob?URL.createObjectURL(c.img):c.img||"";frame.classList.remove("hidden")}
$("closeFrameBtn").onclick=()=>{frame.classList.add("hidden");if(frameImg.src.startsWith("blob:"))URL.revokeObjectURL(frameImg.src);frameImg.src=""};$("deleteCardBtn").onclick=async()=>{if(!currentCard||!confirm("삭제할까?"))return;await deleteCard(currentCard.id);items=items.filter(x=>x.id!==currentCard.id);currentCard=null;frame.classList.add("hidden");render()}
function escapeHTML(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function blobFromDataURL(u){const[m,d]=u.split(","),mime=(m.match(/data:(.*?);/)||[])[1]||"image/jpeg",b=atob(d),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return new Blob([a],{type:mime})}
function blobToDataURL(b){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(b)})}
async function exportData(){const out=[];for(const c of items)out.push({...c,img:c.img instanceof Blob?await blobToDataURL(c.img):c.img});const blob=new Blob([JSON.stringify({version:4,group:GROUP,albums,catalog,items:out})],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=`${GROUP}-poca-backup.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function importData(file){const d=JSON.parse(await file.text());if(!Array.isArray(d.items))throw Error("items가 없는 백업 파일이야.");if(d.albums&&typeof d.albums==="object")albums=d.albums;if(d.catalog&&typeof d.catalog==="object")catalog=d.catalog;normalizeCatalog();for(const x of d.items){const c=normalizeCard({...x,id:x.id||makeId()});if(typeof c.img==="string"&&c.img.startsWith("data:"))c.img=blobFromDataURL(c.img);await saveCard(c)}items=(await getCards()).map(normalizeCard);hydrateCatalogFromItems();saveSettings();renderMemberAdminSelect();renderDynamicFields(getLastAdd());renderAdmin();renderCatalogAdmin();render()}
$("importFile").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{await importData(f);alert("불러오기 완료!")}catch(err){alert("불러오기 실패: "+err.message)}e.target.value=""}
function normalizeCard(c){if(c&&typeof c==="object"){if(typeof c.owned!=="boolean")c.owned=!!c.selected;return c}return c}
function hydrateCatalogFromItems(){for(const c of items){if(c.type!=="앨범"&&catalogTypes.includes(c.type)&&c.detail){catalog[c.type]??=[];if(!catalog[c.type].includes(c.detail))catalog[c.type].push(c.detail)}}normalizeCatalog();saveSettings()}
async function compressAllImages(){if(!items.length)return alert("압축할 포카가 없어.");if(!confirm("모든 포카 이미지를 다시 압축할까?"))return;for(const c of items)if(c.img instanceof Blob){const f=new File([c.img],"card.webp",{type:c.img.type||"image/webp"});c.img=await compressImage(f);await saveCard(c)}items=await getCards();render();alert("압축 완료!")}
async function init(){try{await loadSortable();dbReady=openDB();await dbReady;loadSettings();items=(await getCards()).map(normalizeCard);hydrateCatalogFromItems()}catch(err){console.error(err);alert("저장소를 열지 못했어. 이 웹사이트의 브라우저 저장 기능이 차단되어 있을 수 있어.\n"+(err?.message||err));return}items.sort((a,b)=>(a.order??999999)-(b.order??999999));renderMemberAdminSelect();renderDynamicFields(getLastAdd());renderAdmin();renderCatalogAdmin();render()}searchInput.addEventListener("input",render);init();